spring:
  datasource:
    url: jdbc:mysql://192.168.58.128:3306/mytest
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5

mybatis:
  mapper-locations: classpath*:com/su/dontcare/dao/Mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl